// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl3nVd1bKdedq29qcBPeCcaTKWPfPf9vE',
    appId: '1:76455565345:web:73614cd8537551a4df2b60',
    messagingSenderId: '76455565345',
    projectId: 'chatmate-4adc0',
    authDomain: 'chatmate-4adc0.firebaseapp.com',
    storageBucket: 'chatmate-4adc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEqT6mErYLZqvcW8tF_WcgcZ8qMGdTOI',
    appId: '1:76455565345:android:a82bf572db13b60cdf2b60',
    messagingSenderId: '76455565345',
    projectId: 'chatmate-4adc0',
    storageBucket: 'chatmate-4adc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCofpbWHlQeTRm5IeF9_iAjNT243iAajm0',
    appId: '1:76455565345:ios:1939fe5dca9be42edf2b60',
    messagingSenderId: '76455565345',
    projectId: 'chatmate-4adc0',
    storageBucket: 'chatmate-4adc0.firebasestorage.app',
    iosBundleId: 'com.example.chatmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCofpbWHlQeTRm5IeF9_iAjNT243iAajm0',
    appId: '1:76455565345:ios:1939fe5dca9be42edf2b60',
    messagingSenderId: '76455565345',
    projectId: 'chatmate-4adc0',
    storageBucket: 'chatmate-4adc0.firebasestorage.app',
    iosBundleId: 'com.example.chatmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl3nVd1bKdedq29qcBPeCcaTKWPfPf9vE',
    appId: '1:76455565345:web:3f09d8df86addf0ddf2b60',
    messagingSenderId: '76455565345',
    projectId: 'chatmate-4adc0',
    authDomain: 'chatmate-4adc0.firebaseapp.com',
    storageBucket: 'chatmate-4adc0.firebasestorage.app',
  );
}
